S3_RESPONSE_METADATA = 'ResponseMetadata'
S3_RESPONSE_METADATA_HTTP_STATUS = 'HTTPStatusCode'
S3_RESPONSE_CONTENTS = 'Contents'
S3_RESPONSE_CONTENT_KEY = 'Key'
S3_RESPONSE_NEXT_CONTINUATION_TOKEN = 'NextContinuationToken'
S3_MAX_KEY = 1000

DEFAULT_BUCKET = 'code-database-s3'
ROOT_FOLDER = 'real-challenges'
